// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using _413Final.Models;

namespace _413Final.Migrations
{
    [DbContext(typeof(QuoteContext))]
    [Migration("20220419222003_initial")]
    partial class initial
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.24");

            modelBuilder.Entity("_413Final.Models.Quote", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("author")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("citation")
                        .HasColumnType("TEXT");

                    b.Property<string>("date")
                        .HasColumnType("TEXT");

                    b.Property<string>("quote")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("subject")
                        .HasColumnType("TEXT");

                    b.HasKey("id");

                    b.ToTable("Quotes");

                    b.HasData(
                        new
                        {
                            id = 1,
                            author = "Buddha",
                            quote = "There is no path to happiness; happiness is the path"
                        },
                        new
                        {
                            id = 2,
                            author = "Yoda",
                            quote = "Do or do not. There is no try."
                        },
                        new
                        {
                            id = 3,
                            author = "Colin Powell",
                            quote = "There is no secrets to success. It is the resutl of preparation, hard work, and learning from failure"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
